version: "3.8"

services:
  web:
    # Build from the local Dockerfile
    build: .
    container_name: my-react-app
    # Map port 80 from the container to port 3000 on the host
    ports:
      - "3000:80"
    # If you need environment variables, you could add them here:
    # environment:
    #   - REACT_APP_SOME_VAR=value
