name: Deploy React App

# on:
#   push:
#     branches:
#       - main
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Check if the directory exists, if not clone it
            [ ! -d /srv/projects/repos/splitly ] && git clone https://github.com/sanskaryal/splitly.git
            # Pull latest changes from the main branch
            git pull origin main
            # Rebuild and restart the container
            docker compose down
            docker compose up -d --build
