name: Deploy React App

# on:
#   push:
#     branches:
#       - main
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.11
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Change directory to where your repository is located
            cd /srv/projects/repos/splitly
            # Pull latest changes from the main branch
            git pull origin main
            # Rebuild and restart the container
            docker-compose down
            docker-compose up -d --build
